// Extended types for the enhanced game features

// Ghost AI Types
export type GhostType = 'chaser' | 'patrol' | 'random' | 'smart' | 'ambush';

export interface GhostConfig {
  type: GhostType;
  emoji: string;
  speed: number;
  color: string;
  behavior: string;
  aggroRange: number;
}

export const GHOST_CONFIGS: Record<GhostType, GhostConfig> = {
  chaser: {
    type: 'chaser',
    emoji: '👻',
    speed: 1.0,
    color: '#FFFFFF',
    behavior: 'Directly chases the player',
    aggroRange: 15,
  },
  patrol: {
    type: 'patrol',
    emoji: '🔵',
    speed: 0.7,
    color: '#4169E1',
    behavior: 'Patrols a set path, chases if player is close',
    aggroRange: 5,
  },
  random: {
    type: 'random',
    emoji: '🟣',
    speed: 0.8,
    color: '#9932CC',
    behavior: 'Moves randomly, unpredictable',
    aggroRange: 3,
  },
  smart: {
    type: 'smart',
    emoji: '🔴',
    speed: 0.9,
    color: '#DC143C',
    behavior: 'Predicts player movement, cuts off paths',
    aggroRange: 12,
  },
  ambush: {
    type: 'ambush',
    emoji: '🟢',
    speed: 1.2,
    color: '#228B22',
    behavior: 'Waits near power-ups and goals',
    aggroRange: 4,
  },
};

// Level theme configurations
export type ThemeType = 'classic' | 'jungle' | 'space' | 'underwater' | 'candy' | 'fire' | 'ice';

export interface ThemeConfig {
  id: ThemeType;
  name: string;
  wallColor: string;
  wallGradient: [string, string];
  floorColor: string;
  backgroundColor: string;
  foodEmojis: string[];
  goalEmoji: string;
  ambientEmojis: string[];
  music: string;
}

export const THEME_CONFIGS: Record<ThemeType, ThemeConfig> = {
  classic: {
    id: 'classic',
    name: 'Classic',
    wallColor: '#1a1a1a',
    wallGradient: ['#2a2a2a', '#1a1a1a'],
    floorColor: 'rgba(255, 255, 255, 0.02)',
    backgroundColor: '#0a0a0a',
    foodEmojis: ['🍗', '🍖', '🍔', '🍟', '🍕', '🌭', '🥩', '🥓'],
    goalEmoji: '🏠',
    ambientEmojis: [],
    music: 'classic',
  },
  jungle: {
    id: 'jungle',
    name: 'Jungle',
    wallColor: '#2d5a27',
    wallGradient: ['#3d7a37', '#2d5a27'],
    floorColor: 'rgba(34, 139, 34, 0.1)',
    backgroundColor: '#0a1f0a',
    foodEmojis: ['🍗', '🍖', '🥩', '🍤', '🍣', '🍱'],
    goalEmoji: '🛖',
    ambientEmojis: ['🌿', '🌴', '🦜', '🐒'],
    music: 'jungle',
  },
  space: {
    id: 'space',
    name: 'Space',
    wallColor: '#1a1a3e',
    wallGradient: ['#2a2a5e', '#1a1a3e'],
    floorColor: 'rgba(75, 0, 130, 0.1)',
    backgroundColor: '#0a0a1f',
    foodEmojis: ['🍗', '🍖', '🥩', '🍔', '🍟', '🌭'],
    goalEmoji: '🚀',
    ambientEmojis: ['🛸', '👾', '🌌'],
    music: 'space',
  },
  underwater: {
    id: 'underwater',
    name: 'Underwater',
    wallColor: '#1a4a5a',
    wallGradient: ['#2a6a7a', '#1a4a5a'],
    floorColor: 'rgba(0, 191, 255, 0.1)',
    backgroundColor: '#0a2030',
    foodEmojis: ['🍣', '🍤', '🍗', '🍖', '🦐', '🍱'],
    goalEmoji: '🏝️',
    ambientEmojis: ['🫧', '🌊', '🐙'],
    music: 'underwater',
  },
  candy: {
    id: 'candy',
    name: 'Candy Land',
    wallColor: '#ff69b4',
    wallGradient: ['#ff89c4', '#ff69b4'],
    floorColor: 'rgba(255, 182, 193, 0.1)',
    backgroundColor: '#2a1020',
    foodEmojis: ['🍗', '🍖', '🧀', '🍔', '🍟', '🥓'],
    goalEmoji: '🏰',
    ambientEmojis: ['🎈', '🎀', '💖'],
    music: 'candy',
  },
  fire: {
    id: 'fire',
    name: 'Volcano',
    wallColor: '#8b0000',
    wallGradient: ['#b22222', '#8b0000'],
    floorColor: 'rgba(255, 69, 0, 0.1)',
    backgroundColor: '#1a0505',
    foodEmojis: ['🍖', '🥩', '🍗', '🍔', '🌭', '🍕'],
    goalEmoji: '🏔️',
    ambientEmojis: ['🔥', '💨', '🌋'],
    music: 'fire',
  },
  ice: {
    id: 'ice',
    name: 'Frozen',
    wallColor: '#4682b4',
    wallGradient: ['#5cacdc', '#4682b4'],
    floorColor: 'rgba(173, 216, 230, 0.15)',
    backgroundColor: '#0a1520',
    foodEmojis: ['🍗', '🍖', '🥩', '🍲', '🍜', '🍤'],
    goalEmoji: '🏔️',
    ambientEmojis: ['❄️', '🌨️', '⛄'],
    music: 'ice',
  },
};

// Level configuration with difficulty progression
export interface LevelDefinition {
  level: number;
  rows: number;
  cols: number;
  theme: ThemeType;
  ghostCount: number;
  ghostTypes: GhostType[];
  foodCount: number;
  powerUpChance: number;
  timeLimit?: number; // Optional time limit in seconds
  description: string;
  isBoss?: boolean;
}

export const LEVEL_DEFINITIONS: LevelDefinition[] = [
  // Tutorial/Easy (1-3)
  {
    level: 1,
    rows: 10,
    cols: 10,
    theme: 'classic',
    ghostCount: 1,
    ghostTypes: ['random'],
    foodCount: 5,
    powerUpChance: 0.5,
    description: 'Tutorial',
  },
  {
    level: 2,
    rows: 12,
    cols: 12,
    theme: 'classic',
    ghostCount: 2,
    ghostTypes: ['random'],
    foodCount: 8,
    powerUpChance: 0.4,
    description: 'Getting Started',
  },
  {
    level: 3,
    rows: 13,
    cols: 13,
    theme: 'classic',
    ghostCount: 2,
    ghostTypes: ['random', 'patrol'],
    foodCount: 10,
    powerUpChance: 0.4,
    description: 'New Ghost Type!',
  },

  // Medium (4-7)
  {
    level: 4,
    rows: 14,
    cols: 14,
    theme: 'jungle',
    ghostCount: 3,
    ghostTypes: ['patrol', 'chaser'],
    foodCount: 12,
    powerUpChance: 0.35,
    description: 'Jungle',
  },
  {
    level: 5,
    rows: 15,
    cols: 15,
    theme: 'jungle',
    ghostCount: 3,
    ghostTypes: ['patrol', 'chaser'],
    foodCount: 14,
    powerUpChance: 0.35,
    isBoss: true,
    description: 'Jungle Boss',
  },
  {
    level: 6,
    rows: 15,
    cols: 15,
    theme: 'underwater',
    ghostCount: 4,
    ghostTypes: ['random', 'patrol', 'chaser'],
    foodCount: 15,
    powerUpChance: 0.3,
    description: 'Deep Sea',
  },
  {
    level: 7,
    rows: 16,
    cols: 16,
    theme: 'underwater',
    ghostCount: 4,
    ghostTypes: ['patrol', 'chaser', 'smart'],
    foodCount: 16,
    powerUpChance: 0.3,
    description: 'Ocean Depths',
  },

  // Hard (8-10)
  {
    level: 8,
    rows: 17,
    cols: 17,
    theme: 'space',
    ghostCount: 5,
    ghostTypes: ['chaser', 'smart'],
    foodCount: 18,
    powerUpChance: 0.25,
    description: 'Space',
  },
  {
    level: 9,
    rows: 18,
    cols: 18,
    theme: 'space',
    ghostCount: 5,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 20,
    powerUpChance: 0.25,
    description: 'Asteroid Field',
  },
  {
    level: 10,
    rows: 18,
    cols: 18,
    theme: 'space',
    ghostCount: 6,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 22,
    powerUpChance: 0.2,
    isBoss: true,
    description: 'Alien Boss',
  },

  // Expert (11-15)
  {
    level: 11,
    rows: 19,
    cols: 19,
    theme: 'candy',
    ghostCount: 5,
    ghostTypes: ['patrol', 'smart', 'ambush'],
    foodCount: 20,
    powerUpChance: 0.25,
    description: 'Sweet Escape',
  },
  {
    level: 12,
    rows: 19,
    cols: 19,
    theme: 'candy',
    ghostCount: 6,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 22,
    powerUpChance: 0.2,
    description: 'Sugar Rush',
  },
  {
    level: 13,
    rows: 20,
    cols: 20,
    theme: 'fire',
    ghostCount: 6,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 24,
    powerUpChance: 0.2,
    description: 'Volcano',
  },
  {
    level: 14,
    rows: 20,
    cols: 20,
    theme: 'fire',
    ghostCount: 7,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 25,
    powerUpChance: 0.15,
    description: 'Lava Gauntlet',
  },
  {
    level: 15,
    rows: 21,
    cols: 21,
    theme: 'fire',
    ghostCount: 7,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 26,
    powerUpChance: 0.15,
    isBoss: true,
    description: 'Fire Boss',
  },

  // Master (16-20)
  {
    level: 16,
    rows: 21,
    cols: 21,
    theme: 'ice',
    ghostCount: 7,
    ghostTypes: ['patrol', 'smart', 'ambush'],
    foodCount: 26,
    powerUpChance: 0.2,
    description: 'Frozen Tundra',
  },
  {
    level: 17,
    rows: 22,
    cols: 22,
    theme: 'ice',
    ghostCount: 8,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 28,
    powerUpChance: 0.15,
    description: 'Blizzard',
  },
  {
    level: 18,
    rows: 22,
    cols: 22,
    theme: 'classic',
    ghostCount: 8,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 28,
    powerUpChance: 0.15,
    description: 'Ultimate',
  },
  {
    level: 19,
    rows: 23,
    cols: 23,
    theme: 'classic',
    ghostCount: 9,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 30,
    powerUpChance: 0.1,
    description: 'No Mercy',
  },
  {
    level: 20,
    rows: 25,
    cols: 25,
    theme: 'classic',
    ghostCount: 10,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 35,
    powerUpChance: 0.1,
    isBoss: true,
    description: 'Classic Boss',
  },

  // Nightmare Mode (21-25)
  {
    level: 21,
    rows: 23,
    cols: 23,
    theme: 'jungle',
    ghostCount: 8,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 30,
    powerUpChance: 0.15,
    description: 'Jungle Nightmare',
  },
  {
    level: 22,
    rows: 24,
    cols: 24,
    theme: 'underwater',
    ghostCount: 9,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 32,
    powerUpChance: 0.12,
    description: 'Abyss',
  },
  {
    level: 23,
    rows: 24,
    cols: 24,
    theme: 'space',
    ghostCount: 9,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 34,
    powerUpChance: 0.1,
    description: 'Black Hole',
  },
  {
    level: 24,
    rows: 25,
    cols: 25,
    theme: 'candy',
    ghostCount: 10,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 36,
    powerUpChance: 0.1,
    description: 'Sugar Crash',
  },
  {
    level: 25,
    rows: 25,
    cols: 25,
    theme: 'fire',
    ghostCount: 10,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 38,
    powerUpChance: 0.08,
    isBoss: true,
    description: 'Inferno Boss',
  },

  // Insane Mode (26-30)
  {
    level: 26,
    rows: 25,
    cols: 25,
    theme: 'ice',
    ghostCount: 10,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 38,
    powerUpChance: 0.1,
    description: 'Arctic Storm',
  },
  {
    level: 27,
    rows: 25,
    cols: 25,
    theme: 'jungle',
    ghostCount: 11,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 40,
    powerUpChance: 0.08,
    description: 'Predator',
  },
  {
    level: 28,
    rows: 25,
    cols: 25,
    theme: 'underwater',
    ghostCount: 11,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 40,
    powerUpChance: 0.08,
    description: 'Kraken',
  },
  {
    level: 29,
    rows: 25,
    cols: 25,
    theme: 'space',
    ghostCount: 12,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 42,
    powerUpChance: 0.06,
    description: 'Supernova',
  },
  {
    level: 30,
    rows: 25,
    cols: 25,
    theme: 'fire',
    ghostCount: 12,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 44,
    powerUpChance: 0.05,
    isBoss: true,
    description: 'Dragon King',
  },

  // Legendary Mode (31-35)
  {
    level: 31,
    rows: 25,
    cols: 25,
    theme: 'candy',
    ghostCount: 11,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 42,
    powerUpChance: 0.08,
    description: 'Cavity',
  },
  {
    level: 32,
    rows: 25,
    cols: 25,
    theme: 'ice',
    ghostCount: 12,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 44,
    powerUpChance: 0.06,
    description: 'Permafrost',
  },
  {
    level: 33,
    rows: 25,
    cols: 25,
    theme: 'jungle',
    ghostCount: 12,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 46,
    powerUpChance: 0.05,
    description: 'Apex',
  },
  {
    level: 34,
    rows: 25,
    cols: 25,
    theme: 'underwater',
    ghostCount: 13,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 46,
    powerUpChance: 0.05,
    description: 'Leviathan',
  },
  {
    level: 35,
    rows: 25,
    cols: 25,
    theme: 'space',
    ghostCount: 13,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 48,
    powerUpChance: 0.04,
    isBoss: true,
    description: 'Cosmic Horror',
  },

  // Impossible Mode (36-40)
  {
    level: 36,
    rows: 25,
    cols: 25,
    theme: 'fire',
    ghostCount: 13,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 48,
    powerUpChance: 0.05,
    description: 'Hellfire',
  },
  {
    level: 37,
    rows: 25,
    cols: 25,
    theme: 'candy',
    ghostCount: 14,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 50,
    powerUpChance: 0.04,
    description: 'Diabetic',
  },
  {
    level: 38,
    rows: 25,
    cols: 25,
    theme: 'ice',
    ghostCount: 14,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 50,
    powerUpChance: 0.04,
    description: 'Absolute Zero',
  },
  {
    level: 39,
    rows: 25,
    cols: 25,
    theme: 'classic',
    ghostCount: 14,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 52,
    powerUpChance: 0.03,
    description: 'Purgatory',
  },
  {
    level: 40,
    rows: 25,
    cols: 25,
    theme: 'classic',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 55,
    powerUpChance: 0.02,
    isBoss: true,
    description: 'Demon Lord',
  },

  // God Mode (41-45)
  {
    level: 41,
    rows: 25,
    cols: 25,
    theme: 'jungle',
    ghostCount: 14,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 52,
    powerUpChance: 0.04,
    description: 'Jungle God',
  },
  {
    level: 42,
    rows: 25,
    cols: 25,
    theme: 'underwater',
    ghostCount: 14,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 54,
    powerUpChance: 0.03,
    description: 'Poseidon',
  },
  {
    level: 43,
    rows: 25,
    cols: 25,
    theme: 'space',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 56,
    powerUpChance: 0.03,
    description: 'Galaxy',
  },
  {
    level: 44,
    rows: 25,
    cols: 25,
    theme: 'fire',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 58,
    powerUpChance: 0.02,
    description: 'Phoenix',
  },
  {
    level: 45,
    rows: 25,
    cols: 25,
    theme: 'ice',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 60,
    powerUpChance: 0.02,
    isBoss: true,
    description: 'Frost Giant',
  },

  // Ultimate Challenge (46-50)
  {
    level: 46,
    rows: 25,
    cols: 25,
    theme: 'candy',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 58,
    powerUpChance: 0.03,
    description: 'Sugar Demon',
  },
  {
    level: 47,
    rows: 25,
    cols: 25,
    theme: 'classic',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 60,
    powerUpChance: 0.02,
    description: 'Chaos',
  },
  {
    level: 48,
    rows: 25,
    cols: 25,
    theme: 'jungle',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 62,
    powerUpChance: 0.02,
    description: 'Extinction',
  },
  {
    level: 49,
    rows: 25,
    cols: 25,
    theme: 'fire',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 65,
    powerUpChance: 0.01,
    description: 'Armageddon',
  },
  {
    level: 50,
    rows: 25,
    cols: 25,
    theme: 'classic',
    ghostCount: 15,
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: 70,
    powerUpChance: 0.01,
    isBoss: true,
    description: 'TIGER WORLD GOD',
  },
];

// Get level definition, with fallback for levels beyond 20
export function getLevelDefinition(level: number): LevelDefinition {
  if (level <= LEVEL_DEFINITIONS.length) {
    return LEVEL_DEFINITIONS[level - 1];
  }

  // Generate dynamic levels for endless mode
  const baseLevel = LEVEL_DEFINITIONS[LEVEL_DEFINITIONS.length - 1];
  const extraDifficulty = level - LEVEL_DEFINITIONS.length;

  return {
    level,
    rows: Math.min(25, baseLevel.rows + Math.floor(extraDifficulty / 2)),
    cols: Math.min(25, baseLevel.cols + Math.floor(extraDifficulty / 2)),
    theme: Object.keys(THEME_CONFIGS)[level % Object.keys(THEME_CONFIGS).length] as ThemeType,
    ghostCount: Math.min(15, baseLevel.ghostCount + Math.floor(extraDifficulty / 2)),
    ghostTypes: ['chaser', 'smart', 'ambush'],
    foodCount: Math.min(50, baseLevel.foodCount + extraDifficulty),
    powerUpChance: Math.max(0.05, baseLevel.powerUpChance - extraDifficulty * 0.01),
    description: `Endless Mode - Level ${level}`,
    isBoss: level % 5 === 0,
  };
}
